services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: les-echos-api
    restart: always
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb://lesechos:lesechos-password@localhost:27017/lesechos
    command: npm run start:prod
