services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d
      - data-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://lesechos:lesechos-password@mongodb:27017/lesechos
      ME_CONFIG_BASICAUTH: false
      # http://localhost:8081/db/lesechos to access les echos db
    depends_on:
      - mongodb
volumes:
  data-volume:
